apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
  name: express-app-pipeline
spec:
  params:
    - name: image-repo
      type: string
      description: Repo where Docker image will be stored
    - name: app-name
      type: string
      description: Name of application
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  tasks:
    - name: clone-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/express-app-sohaib-ashraf
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: run-tests
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: ARGS
          value:
            - install-ci-test
      runAfter:
        - clone-repository
    - name: build-image
      taskRef:
        kind: ClusterTask
        name: buildah
      runAfter:
        - run-tests
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: kustomize-build
      runAfter:
        - build-image
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: app-namespace
          value:  "$(context.pipelineRun.namespace)"
        - name: image-with-tag
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: test-deploy
      taskRef:
        kind: Task
        name: test-deploy
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: app-namespace
          value: "$(context.pipelineRun.namespace)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      runAfter:
        - kustomize-build
    - name: gitops
      taskRef:
        kind: Task
        name: commit-manifest
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: sha
          value: "$(tasks.clone-repository.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      runAfter:
        - test-deploy