apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: react-app-pipeline-
spec:
  serviceAccountName: build-bot-react
  pipelineRef:
    name: react-app-pipeline
  params:
    - name: image-repo
      value: quay.io/sohaib_ashraf_ibm/squad-3-react-app
    - name: app-name
      value: react-app
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi